/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: DJMaesen (https://sketchfab.com/bumstrum)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ancient-tree-960fb92d7192458daeaf4282cc6193e2
Title: Ancient Tree
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/scene.gltf");
  return (
    <group {...props} dispose={null}>
      <group
        position={[13.352, 477.099, 391.736]}
        rotation={[3.063, -0.295, -0.107]}
        scale={1.174}
      >
        <mesh
          geometry={nodes.branch_3_ancientTree_0.geometry}
          material={materials.ancientTree}
        />
        <mesh
          geometry={nodes.leaves_2_leaves_0.geometry}
          material={materials.leaves}
          position={[30.066, -6.39, -187.062]}
          rotation={[-0.877, -0.389, -0.924]}
        />
      </group>
      <group
        position={[-366.426, 407.571, -26.332]}
        rotation={[-0.716, 1.533, 1.429]}
        scale={0.829}
      >
        <mesh
          geometry={nodes.branch_7_ancientTree_0.geometry}
          material={materials.ancientTree}
        />
        <mesh
          geometry={nodes.leaves_3_leaves_0.geometry}
          material={materials.leaves}
          position={[30.066, -6.39, -187.062]}
          rotation={[-0.877, -0.389, -0.924]}
        />
      </group>
      <group
        position={[-316.923, 513.575, 64.948]}
        rotation={[2.525, 0.612, -1.807]}
        scale={1.034}
      >
        <mesh
          geometry={nodes.branch_10_ancientTree_0.geometry}
          material={materials.ancientTree}
        />
        <mesh
          geometry={nodes.leaves_4_leaves_0.geometry}
          material={materials.leaves}
          position={[30.066, -6.39, -187.062]}
          rotation={[-0.877, -0.389, -0.924]}
        />
      </group>
      <group
        position={[-44.874, 607.917, -431.847]}
        rotation={[0.526, -0.192, 2.938]}
        scale={0.834}
      >
        <mesh
          geometry={nodes.branch_11_ancientTree_0.geometry}
          material={materials.ancientTree}
        />
        <mesh
          geometry={nodes.leaves_5_leaves_0.geometry}
          material={materials.leaves}
          position={[25.797, -5.482, -160.499]}
          rotation={[-0.877, -0.389, -0.924]}
        />
      </group>
      <group
        position={[-285.006, 605.428, -33.163]}
        rotation={[1.154, 0.81, 2.483]}
        scale={0.96}
      >
        <mesh
          geometry={nodes.branch_12_ancientTree_0.geometry}
          material={materials.ancientTree}
        />
        <mesh
          geometry={nodes.leaves_6_leaves_0.geometry}
          material={materials.leaves}
          position={[30.066, -6.39, -187.062]}
          rotation={[-0.877, -0.389, -0.924]}
        />
      </group>
      <group
        position={[185.653, 340.04, 127.222]}
        rotation={[1.34, -1.246, 2.55]}
        scale={0.809}
      >
        <mesh
          geometry={nodes.branch_15_ancientTree_0.geometry}
          material={materials.ancientTree}
        />
        <mesh
          geometry={nodes.leaves_7_leaves_0.geometry}
          material={materials.leaves}
          position={[30.066, -6.39, -187.062]}
          rotation={[-0.877, -0.389, -0.924]}
        />
      </group>
      <group
        position={[189.414, 606.669, 11.077]}
        rotation={[2.075, -0.86, -2.657]}
        scale={0.967}
      >
        <mesh
          geometry={nodes.branch_19_ancientTree_0.geometry}
          material={materials.ancientTree}
        />
        <mesh
          geometry={nodes.leaves_8_leaves_0.geometry}
          material={materials.leaves}
          position={[30.066, -6.39, -187.062]}
          rotation={[-0.877, -0.389, -0.924]}
        />
      </group>
      <mesh
        geometry={nodes.ancientTREE_ancientTree_0.geometry}
        material={materials.ancientTree}
      />
      <mesh
        geometry={nodes.leaves_leaves_0.geometry}
        material={materials.leaves}
        position={[-45.708, 597.857, -46.09]}
      />
    </group>
  );
}

useGLTF.preload("/scene.gltf");
